#!/bin/sh
# SPDX-FileCopyrightText: 2026 Hugo Duda
# SPDX-License-Identifier: MIT

set -eu

repository_root=$(git rev-parse --show-toplevel)
exec python3 "$repository_root/tools/commit_message.py" file "$1"
