#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hugo Duda
# SPDX-License-Identifier: MIT

"""Generate and verify the VMNL public-API documentation inventories."""

from __future__ import annotations

import argparse
import dataclasses
import html
import os
from pathlib import Path
import re
import subprocess
import sys
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
API_ROOT = ROOT / "docs" / "api"
MATRIX_PATH = API_ROOT / "maintenance" / "coverage_matrix.md"
SNAPSHOT_PATH = API_ROOT / "maintenance" / "public_api_snapshot.md"
SYMBOL_INDEX_PATH = API_ROOT / "appendices" / "public_symbol_index.md"
METHOD_INDEX_PATH = API_ROOT / "appendices" / "method_index.md"
EXPECTED_PUBLIC_API_VERSION = "0.52.0"
PUBLIC_API_NIGHTLY = "nightly-2026-03-12"
PUBLIC_API_COMMAND = (
    "cargo",
    f"+{PUBLIC_API_NIGHTLY}",
    "public-api",
    "--manifest-path",
    "crates/vmnl_graphics/Cargo.toml",
    "--target-dir",
    "target/api-public-api",
    "--omit",
    "blanket-impls",
)
MACRO_API_COMMAND = (
    "cargo",
    f"+{PUBLIC_API_NIGHTLY}",
    "public-api",
    "--manifest-path",
    "crates/vmnl_macros/Cargo.toml",
    "--target-dir",
    "target/api-public-api",
    "--omit",
    "blanket-impls",
)
FACADE_API_COMMAND = (
    "cargo",
    f"+{PUBLIC_API_NIGHTLY}",
    "public-api",
    "--manifest-path",
    "crates/vmnl/Cargo.toml",
    "--target-dir",
    "target/api-public-api",
    "--omit",
    "blanket-impls",
)
PUBLIC_PATH_ALIASES = {
    "vmnl::ShaderSource": "vmnl::common::ShaderSource",
    "vmnl::raw::ShaderSource": "vmnl::common::ShaderSource",
}
ALLOWED_KINDS = {"struct", "enum", "trait", "alias", "macro"}
GENERATED_NOTICE = "<!-- Generated by tools/api_docs.py; do not edit. -->"
WINDOW_CONFIGURATION_METHODS = {
    "get_content_scale",
    "get_framebuffer_size",
    "get_opacity",
    "get_position",
    "get_size",
    "get_title",
    "height",
    "monitor",
    "opacity",
    "set_aspect_ratio",
    "set_clear_color",
    "set_position",
    "set_size",
    "set_size_limits",
    "set_title",
    "width",
}
WINDOW_LIFECYCLE_METHODS = {
    "close",
    "focus",
    "hide",
    "iconify",
    "is_focused",
    "is_iconified",
    "is_maximized",
    "is_open",
    "is_ready",
    "is_visible",
    "maximize",
    "restore",
    "show",
}
WINDOW_EVENT_METHODS = {
    "get_time",
    "get_timer_frequency",
    "get_timer_value",
    "input",
    "poll_events",
    "post_empty_event",
    "set_error_callback",
    "set_time",
    "unset_error_callback",
    "wait_events",
    "wait_events_timeout",
}


class ApiDocsError(RuntimeError):
    """A deterministic API-documentation validation error."""


@dataclasses.dataclass(frozen=True, order=True)
class PublicItem:
    kind: str
    symbol: str


@dataclasses.dataclass(frozen=True, order=True)
class PublicMethod:
    owner: str
    name: str


@dataclasses.dataclass(frozen=True)
class CoverageRow:
    item: PublicItem
    page_label: str
    page_target: str
    rustdoc_label: str
    rustdoc_target: str
    evidence: str


@dataclasses.dataclass(frozen=True)
class Surface:
    text: str
    items: tuple[PublicItem, ...]
    methods: tuple[PublicMethod, ...]
    facade_exports: tuple[str, ...] = ()


ITEM_RE = re.compile(
    r"^(?:#\[[^]]+]\s+)*pub\s+(?:unsafe\s+)?(?P<kind>struct|enum|trait|type|union)\s+"
    r"(?P<symbol>vmnl(?:::[A-Za-z_][A-Za-z0-9_]*)+)(?:<|\s|\{|;|=|:|\(|$)"
)
MACRO_RE = re.compile(
    r"^pub\s+(?:proc_)?macro(?:_derive)?\s+"
    r"(?P<symbol>vmnl(?:::[A-Za-z_][A-Za-z0-9_]*)+)(?:!|\s|\(|\{|$)"
)
METHOD_RE = re.compile(
    r"^pub\s+(?:const\s+)?(?:async\s+)?(?:unsafe\s+)?fn\s+"
    r"(?P<path>vmnl::.+?)\s*\("
)
LINK_RE = re.compile(r"^\[(?P<label>[^]]+)]\((?P<target>[^)]+)\)$")
KNOWN_LINE_RES = (
    re.compile(r"^(?:pub\s+)?mod\s+"),
    re.compile(r"^pub\s+use\s+"),
    re.compile(r"^(?:pub\s+)?(?:unsafe\s+)?impl(?:<|\s)"),
    re.compile(r"^impl(?:<|\s)"),
    re.compile(r"^pub\s+(?:const|static)\s+"),
    re.compile(r'^pub\s+(?:unsafe\s+)?(?:extern\s+"[^"]+"\s+)?fn\s+'),
    re.compile(r"^pub\s+vmnl::"),  # enum variants in cargo-public-api output
    re.compile(r"^pub\s+[A-Za-z_][A-Za-z0-9_]*\s*:"),  # public fields
    re.compile(r"^(?:type|const)\s+"),
    re.compile(r"^(?:where|for)\b"),
    re.compile(r"^[{}(),;]"),
    re.compile(r"^[A-Za-z_][A-Za-z0-9_]*\s*:"),
    re.compile(r"^#"),
)
REEXPORT_RE = re.compile(r"^pub use (?P<symbol>vmnl(?:::[A-Za-z_][A-Za-z0-9_]*)+)$")


def strip_generics(path: str) -> str:
    """Remove balanced generic argument lists from a rustdoc path."""
    result: list[str] = []
    depth = 0
    for char in path:
        if char == "<":
            depth += 1
        elif char == ">" and depth:
            depth -= 1
        elif depth == 0:
            result.append(char)
    return "".join(result)


def parse_facade_exports(text: str) -> tuple[str, ...]:
    exports = {
        match.group("symbol")
        for raw_line in text.splitlines()
        if (match := REEXPORT_RE.match(raw_line.strip())) is not None
    }
    if not exports:
        raise ApiDocsError("vmnl facade inventory contains no public reexports")
    return tuple(sorted(exports))


def parse_surface(text: str, facade_text: str | None = None) -> Surface:
    text = text.replace("vmnl_graphics::", "vmnl::").replace(
        "pub mod vmnl_graphics", "pub mod vmnl"
    )
    text = re.sub(
        r"pub proc macro vmnl_macros::#\[derive\(([A-Za-z_][A-Za-z0-9_]*)\)\]",
        r"pub macro vmnl::raw::\1",
        text,
    ).replace("pub mod vmnl_macros", "pub mod vmnl::raw")
    items: set[PublicItem] = set()
    methods: set[PublicMethod] = set()
    unknown: list[str] = []

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith(("Public API", "RUSTDOCFLAGS")):
            continue

        item_match = ITEM_RE.match(line)
        if item_match:
            kind = item_match.group("kind")
            if kind == "type":
                kind = "alias"
            elif kind == "union":
                kind = "struct"
            symbol = item_match.group("symbol")
            symbol = PUBLIC_PATH_ALIASES.get(symbol, symbol)
            if "::__private" not in symbol:
                items.add(PublicItem(kind, symbol))
            continue

        macro_match = MACRO_RE.match(line)
        if macro_match:
            symbol = macro_match.group("symbol")
            if "::__private" not in symbol:
                items.add(PublicItem("macro", symbol))
            continue

        method_match = METHOD_RE.match(line)
        if method_match:
            path = strip_generics(method_match.group("path"))
            if "::__private" not in path and "::" in path:
                owner, name = path.rsplit("::", 1)
                owner = PUBLIC_PATH_ALIASES.get(owner, owner)
                methods.add(PublicMethod(owner, name))
            continue

        if not any(pattern.match(line) for pattern in KNOWN_LINE_RES):
            unknown.append(line)

    item_symbols = {item.symbol for item in items if item.kind != "alias"}
    items = {
        item
        for item in items
        if item.kind != "alias" or item.symbol.rsplit("::", 1)[0] not in item_symbols
    }

    canonical_by_name: dict[str, set[str]] = {}
    for item in items:
        if item.kind != "macro":
            canonical_by_name.setdefault(item.symbol.rsplit("::", 1)[-1], set()).add(
                item.symbol
            )
    canonical_methods: set[PublicMethod] = set()
    for method in methods:
        owner = method.owner
        if owner not in item_symbols:
            candidates = canonical_by_name.get(owner.rsplit("::", 1)[-1], set())
            if len(candidates) == 1:
                owner = next(iter(candidates))
        canonical_methods.add(PublicMethod(owner, method.name))

    if unknown:
        preview = "\n".join(f"  {line}" for line in unknown[:8])
        raise ApiDocsError(f"unknown cargo-public-api inventory format:\n{preview}")
    if not items:
        raise ApiDocsError("cargo-public-api inventory contains no public items")

    return Surface(
        text.rstrip() + "\n",
        tuple(sorted(items)),
        tuple(sorted(canonical_methods)),
        parse_facade_exports(facade_text) if facade_text is not None else (),
    )


def parse_link(cell: str, label: str) -> tuple[str, str]:
    match = LINK_RE.match(cell.strip())
    if not match:
        raise ApiDocsError(f"{label} must be one Markdown link: {cell!r}")
    return match.group("label"), match.group("target")


def parse_matrix(path: Path = MATRIX_PATH) -> tuple[CoverageRow, ...]:
    rows: list[CoverageRow] = []
    seen: set[PublicItem] = set()
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.startswith("|"):
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if not cells or cells[0] in {"Kind", "---", ":---"} or set(cells[0]) <= {"-", ":"}:
            continue
        if len(cells) != 5:
            raise ApiDocsError(f"{path}:{line_number}: expected 5 matrix columns")
        kind, symbol_cell, page_cell, rustdoc_cell, evidence = cells
        if kind not in ALLOWED_KINDS:
            raise ApiDocsError(f"{path}:{line_number}: unknown item kind {kind!r}")
        symbol = symbol_cell.strip("`")
        if not symbol.startswith("vmnl::"):
            raise ApiDocsError(f"{path}:{line_number}: invalid public symbol {symbol!r}")
        item = PublicItem(kind, symbol)
        if item in seen:
            raise ApiDocsError(f"{path}:{line_number}: duplicate matrix item {kind} {symbol}")
        seen.add(item)
        page_label, page_target = parse_link(page_cell, "canonical page")
        rustdoc_label, rustdoc_target = parse_link(rustdoc_cell, "Rustdoc")
        if not evidence or evidence == "—":
            raise ApiDocsError(f"{path}:{line_number}: missing evidence for {symbol}")
        rows.append(
            CoverageRow(
                item, page_label, page_target, rustdoc_label, rustdoc_target, evidence
            )
        )
    if not rows:
        raise ApiDocsError(f"{path}: no coverage rows")
    return tuple(rows)


def markdown_anchor(text: str) -> str:
    text = re.sub(r"<[^>]+>", "", text).strip().lower()
    text = re.sub(r"[^a-z0-9 _-]", "", text)
    return re.sub(r"[ _]+", "-", text).strip("-")


def split_target(target: str) -> tuple[str, str | None]:
    if "#" in target:
        path, anchor = target.split("#", 1)
        return path, anchor
    return target, None


def local_target(base: Path, target: str) -> tuple[Path, str | None] | None:
    path_text, anchor = split_target(target)
    if re.match(r"^[a-z][a-z0-9+.-]*://", path_text):
        return None
    return (base / path_text).resolve(), anchor


def document_anchors(path: Path) -> set[str]:
    content = path.read_text(encoding="utf-8")
    anchors = {
        markdown_anchor(match.group(1))
        for match in re.finditer(r"^#{1,6}\s+(.+?)\s*$", content, re.MULTILINE)
    }
    anchors.update(re.findall(r"<a\s+(?:name|id)=['\"]([^'\"]+)", content))
    return anchors


def validate_matrix_files(rows: Iterable[CoverageRow], matrix_path: Path = MATRIX_PATH) -> None:
    for row in rows:
        resolved = local_target(matrix_path.parent, row.page_target)
        if resolved is None:
            raise ApiDocsError(f"canonical page for {row.item.symbol} must be local")
        page, anchor = resolved
        if not page.is_file():
            raise ApiDocsError(f"missing canonical page for {row.item.symbol}: {page}")
        if anchor and anchor not in document_anchors(page):
            raise ApiDocsError(f"missing page anchor #{anchor} for {row.item.symbol}: {page}")


def validate_coverage(surface: Surface, rows: Iterable[CoverageRow]) -> None:
    surface_items = set(surface.items)
    matrix_items = {row.item for row in rows}
    missing = sorted(surface_items - matrix_items)
    stale = sorted(matrix_items - surface_items)
    if missing or stale:
        details: list[str] = []
        if missing:
            details.append("missing from matrix:\n" + "\n".join(f"  {x.kind} {x.symbol}" for x in missing))
        if stale:
            details.append("not present in public surface:\n" + "\n".join(f"  {x.kind} {x.symbol}" for x in stale))
        raise ApiDocsError("coverage matrix mismatch:\n" + "\n".join(details))


def validate_facade_reexports(surface: Surface) -> None:
    if not surface.facade_exports:
        raise ApiDocsError("vmnl facade exports were not inventoried")
    required: set[str] = set()
    namespaces = {"common", "d2", "d3", "raw"}
    for item in surface.items:
        segments = item.symbol.split("::")[1:]
        if not segments:
            continue
        exported = segments[0] if segments[0] in namespaces else segments[-1]
        required.add(f"vmnl::{exported}")
    for public_alias in PUBLIC_PATH_ALIASES:
        segments = public_alias.split("::")[1:]
        exported = segments[0] if segments[0] in namespaces else segments[-1]
        required.add(f"vmnl::{exported}")
    missing = sorted(required - set(surface.facade_exports))
    if missing:
        values = "\n".join(f"  {name}" for name in missing)
        raise ApiDocsError(f"public implementation items are not reexported by vmnl:\n{values}")


def row_by_symbol(rows: Iterable[CoverageRow]) -> dict[str, CoverageRow]:
    result: dict[str, CoverageRow] = {}
    for row in rows:
        if row.item.kind == "macro":
            continue
        result[row.item.symbol] = row
    return result


def method_anchor(row: CoverageRow, method: PublicMethod) -> str:
    prefix = "tymethod" if row.item.kind == "trait" else "method"
    return f"{prefix}.{method.name}"


def method_page(row: CoverageRow, method: PublicMethod) -> tuple[str, str]:
    if method.owner != "vmnl::Window":
        return row.page_label, row.page_target
    if method.name in WINDOW_CONFIGURATION_METHODS:
        return "Window configuration", "../reference/window/configuration.md"
    if method.name in WINDOW_LIFECYCLE_METHODS:
        return "Window lifecycle", "../reference/window/lifecycle.md"
    if method.name in WINDOW_EVENT_METHODS:
        return "Events and timers", "../reference/window/events/event_processing_and_timers.md"
    if method.name == "render":
        return "Window rendering", "../reference/window/rendering/README.md"
    if "polling" in method.name:
        return "Window polling", "../reference/window/polling.md"
    return row.page_label, row.page_target


def render_snapshot(surface: Surface) -> str:
    return (
        f"{GENERATED_NOTICE}\n"
        "# Public API snapshot\n\n"
        f"Generated with `cargo-public-api 0.52.0`, `{PUBLIC_API_NIGHTLY}`, "
        "omitting blanket implementations only. Update with `just docs-api-update`.\n\n"
        "```text\n"
        f"{surface.text}```\n"
    )


def render_symbol_index(rows: Iterable[CoverageRow]) -> str:
    lines = [
        GENERATED_NOTICE,
        "# Public symbol index",
        "",
        "| Kind | Symbol | Canonical page | Rustdoc |",
        "|---|---|---|---|",
    ]
    for row in sorted(rows, key=lambda value: (value.item.symbol, value.item.kind)):
        lines.append(
            f"| {row.item.kind} | `{row.item.symbol}` | "
            f"[{row.page_label}]({row.page_target}) | "
            f"[{row.rustdoc_label}]({row.rustdoc_target}) |"
        )
    return "\n".join(lines) + "\n"


def render_method_index(surface: Surface, rows: Iterable[CoverageRow]) -> str:
    owners = row_by_symbol(rows)
    lines = [
        GENERATED_NOTICE,
        "# Method index",
        "",
        "| Owner | Method | Canonical page | Rustdoc method |",
        "|---|---|---|---|",
    ]
    unresolved: list[PublicMethod] = []
    for method in surface.methods:
        row = owners.get(method.owner)
        if row is None:
            unresolved.append(method)
            continue
        anchor = method_anchor(row, method)
        page_label, page_target = method_page(row, method)
        lines.append(
            f"| `{method.owner}` | `{method.name}` | "
            f"[{page_label}]({page_target}) | "
            f"[`{method.name}`]({row.rustdoc_target}#{anchor}) |"
        )
    if unresolved:
        values = "\n".join(f"  {method.owner}::{method.name}" for method in unresolved)
        raise ApiDocsError(f"public methods have no owning matrix item:\n{values}")
    return "\n".join(lines) + "\n"


def render_outputs(surface: Surface, rows: tuple[CoverageRow, ...]) -> dict[Path, str]:
    return {
        SNAPSHOT_PATH: render_snapshot(surface),
        SYMBOL_INDEX_PATH: render_symbol_index(rows),
        METHOD_INDEX_PATH: render_method_index(surface, rows),
    }


def validate_method_anchors(surface: Surface, rows: Iterable[CoverageRow]) -> None:
    owners = row_by_symbol(rows)
    for method in surface.methods:
        row = owners.get(method.owner)
        if row is None:
            continue
        resolved = local_target(MATRIX_PATH.parent, row.rustdoc_target)
        if resolved is None:
            continue
        rustdoc, _ = resolved
        if not rustdoc.is_file():
            raise ApiDocsError(f"missing Rustdoc page for {method.owner}::{method.name}: {rustdoc}")
        anchor = method_anchor(row, method)
        content = rustdoc.read_text(encoding="utf-8")
        escaped = html.escape(anchor, quote=True)
        if f'id="{escaped}"' not in content and f"id='{escaped}'" not in content:
            raise ApiDocsError(
                f"missing Rustdoc method anchor #{anchor} for {method.owner}::{method.name}"
            )


def read_surface_file(path: Path) -> Surface:
    text = path.read_text(encoding="utf-8")
    return parse_surface(text, text)


def command_surface() -> Surface:
    override = os.environ.get("VMNL_API_SURFACE_FILE")
    if override:
        return read_surface_file(Path(override))

    version = subprocess.run(
        ("cargo", "public-api", "--version"),
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    ).stdout
    if EXPECTED_PUBLIC_API_VERSION not in version:
        raise ApiDocsError(
            f"cargo-public-api {EXPECTED_PUBLIC_API_VERSION} required, observed {version.strip()}"
        )
    outputs: list[str] = []
    for command in (PUBLIC_API_COMMAND, MACRO_API_COMMAND):
        completed = subprocess.run(
            command,
            cwd=ROOT,
            check=True,
            text=True,
            stdout=subprocess.PIPE,
        )
        outputs.append(completed.stdout)
    facade = subprocess.run(
        FACADE_API_COMMAND,
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return parse_surface("\n".join(outputs), facade.stdout)


def update(surface: Surface) -> None:
    rows = parse_matrix()
    validate_facade_reexports(surface)
    validate_matrix_files(rows)
    validate_coverage(surface, rows)
    for path, content in render_outputs(surface, rows).items():
        path.write_text(content, encoding="utf-8")


def check(surface: Surface) -> None:
    rows = parse_matrix()
    validate_facade_reexports(surface)
    validate_matrix_files(rows)
    validate_coverage(surface, rows)
    expected = render_outputs(surface, rows)
    stale = [path for path, content in expected.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]
    if stale:
        values = "\n".join(f"  {path.relative_to(ROOT)}" for path in stale)
        raise ApiDocsError(f"generated API documentation is stale:\n{values}\nrun: just docs-api-update")
    validate_method_anchors(surface, rows)


def arguments(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("check", "update"))
    parser.add_argument(
        "--surface-file",
        type=Path,
        help="read a cargo-public-api text fixture instead of invoking Cargo",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = arguments(sys.argv[1:] if argv is None else argv)
    try:
        surface = read_surface_file(args.surface_file) if args.surface_file else command_surface()
        if args.mode == "update":
            update(surface)
        else:
            check(surface)
    except (ApiDocsError, OSError, subprocess.CalledProcessError) as error:
        print(f"api-docs: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
